export const PLAYERS_NEEDED_TO_START = 2;
export const COUNTDOWN_TIME = 3;
export const LOBBY_TRANSITION_TO_COUNTDOWN_TIME = 3;

export const THEME_SELECTION_TIME = 5;
export const GAME_TIME = 60;
export const FINISHED_TRANSITION_TO_LOBBY_TIME = 10;

/* INTERVALS */
export const REQUEST_CURRENT_TEXT_INTERVAL = 0.1;
export const CALCULATE_PLAYER_POSITIONS_INTERVAL = 0.2;
export const SEND_PLAYER_POSITIONS_INTERVAL = 0.3;
export const CHECK_PLAYERS_COMPLETED_INTERVAL = 1;