export const PLAYERS_NEEDED_TO_START = 2;
export const COUNTDOWN_TIME = 1;
export const LOBBY_TRANSITION_TO_COUNTDOWN_TIME = 1;

export const THEME_SELECTION_TIME = 2;
export const GAME_TIME =50;
export const FINISHED_TRANSITION_TO_LOBBY_TIME = 3;

/* INTERVALS */
export const REQUEST_CURRENT_TEXT_INTERVAL = 0.5;
export const CALCULATE_PLAYER_POSITIONS_INTERVAL = 0.7;
export const SEND_PLAYER_POSITIONS_INTERVAL = 0.9;