export default {
    'Default': [
        "The sun did not shine. It was too wet to play. So we sat in the house. All that cold, cold, wet day.",
        "I wish you to know that you have been the last dream of my soul.",
        "In our village, folks say God crumbles up the old moon into stars.",
        "Once upon a midnight dreary, while I pondered, weak and weary,",
        "Over many a quaint and curious volume of forgotten lore,",
        "While I nodded, nearly napping, suddenly there came a tapping,",
        "As of someone gently rapping, rapping at my chamber door.",
        "Tis some visitor, I muttered, tapping at my chamber door -",
        "Only this, and nothing more.",
        "Ah, distinctly I remember it was in the bleak December;",
        "And each separate dying ember wrought its ghost upon the floor.",
        "Eagerly I wished the morrow; - vainly I had sought to borrow",
        "From my books surcease of sorrow - sorrow for the lost Lenore -",
        "For the rare and radiant maiden whom the angels name Lenore -",
        "Nameless here for evermore.",
    ],
    'Psychology': [
        "The one thing that doesn't abide by majority rule is a person's conscience.",
        "There is nothing either good or bad, but thinking makes it so.",
        "Hell is other people.",
        "The unexamined life is not worth living.",
        "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.",
        "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes of mind.",
        "What we think, we become.",
        "The purpose of psychology is to give us a completely different idea of the things we know best.",
        "The only person you are destined to become is the person you decide to be.",
    ],
    'Javascript': [
        "const greet = (name) => `Hello, ${name}! Welcome to JavaScript!`;",
        "let arr = [1, 2, 3, 4, 5];arr.map(num => num * 2);",
        "let promise = new Promise((resolve, reject) => {setTimeout(() => resolve('Promise resolved!'), 1000);});",
        "let obj = {a: 1, b: 2, c: 3};for (let key in obj) {console.log(`key: ${key}, value: ${obj[key]}`);}",
        "function fibonacci(num) {if (num <= 1) return 1;return fibonacci(num - 1) + fibonacci(num - 2);}",
        "let arr = [1, 2, 3, 4, 5];let [first, ...rest] = arr;console.log(first, rest);",
        "let str = 'Hello, JavaScript!';console.log(str.split('').reverse().join(''));",
        "let arr = [1, 2, 3, 4, 5];let sum = arr.reduce((acc, val) => acc + val, 0);console.log(sum);",
        "let str = 'Hello, JavaScript!';console.log([...str].length === str.length);",
        "let arr = [1, 2, 3, 4, 5];console.log(Math.max(...arr));",
    ],
    'LeagueOfLegends': [
        "Once upon a time, in the city of Piltover, a young inventor named Heimerdinger was working on a new kind of turret. Suddenly, a yordle named Teemo came running into his lab, chased by a giant robot. With a quick adjustment, Heimerdinger's turret sprang to life and defeated the robot, saving Teemo.",
        "In the depths of the Shadow Isles, Thresh, the Chain Warden, was collecting souls when he came across a peculiar one. It was bright and full of life, unlike the others. It was the soul of Lucian's wife, Senna. Thresh decided to keep it, sparking a rivalry that would span across realms.",
        "In the Freljord, Ashe, the Frost Archer, was leading her tribe when they were attacked by the Winter's Claw, led by Sejuani. Despite being outnumbered, Ashe's strategic mind and exceptional archery skills led her tribe to victory, solidifying her position as the leader of the Avarosan.",
        "In the Plague Jungles, Amumu, the Sad Mummy, was wandering alone when he stumbled upon a party being thrown by the yordles. They invited him to join, and for the first time in a long time, Amumu felt a bit of happiness. But as the party ended, he was once again left alone, continuing his eternal search for a friend.",
        "In the city of Noxus, Darius, the Hand of Noxus, was preparing for a battle against Demacia. As he was strategizing, his brother Draven burst in, boasting about his latest victory in the arena. Darius just shook his head and went back to his plans, knowing that Draven's theatrics were just part of his charm.",
        "In the bustling city of Zaun, Ekko, the Boy Who Shattered Time, was tinkering with his time device when he accidentally sent himself back in time. He ended up meeting a younger version of himself and gave him some advice that would change his life.",
        "In the celestial realm, Soraka, the Starchild, was weaving constellations when she noticed a star falling towards Runeterra. She descended to the mortal realm to guide the star back to the sky, spreading hope and healing wherever she went.",
        "In the ancient Shuriman desert, Azir, the Emperor of the Sands, was rebuilding his empire when he discovered an ancient artifact. The artifact turned out to be a map to a hidden oasis, which Azir used to provide water for his people.",
        "In the heart of Demacia, Lux, the Lady of Luminosity, was practicing her light magic when she accidentally created a rainbow that could be seen throughout the kingdom. The people of Demacia were amazed and it became a day of celebration.",
        "In the twisted realm of the Void, Kassadin, the Voidwalker, was battling void creatures when he found a clue to his lost family. This gave him renewed hope and strength, pushing him further into the abyss.",
        "In the depths of the ocean, Nami, the Tidecaller, was on a quest to find the moonstone to save her people. Along the way, she encountered various sea creatures and overcame many challenges, proving her worth as the Tidecaller.",
        "In the icy tundra of the Freljord, Lissandra, the Ice Witch, was plotting her next move when she discovered an ancient ice crystal with immense power. With this crystal, she planned to bring an eternal winter to the Freljord.",
        "In the mystical realm of Ionia, Yasuo, the Unforgiven, was on the run when he encountered a group of bandits. Using his superior swordsmanship and the power of the wind, he defeated them and continued his journey to clear his name.",
        "In the shadowy underworld of Bilgewater, Pyke, the Bloodharbor Ripper, was hunting his next target when he stumbled upon a hidden treasure. However, instead of gold and jewels, the treasure turned out to be a list of all the captains who had wronged him.",
        "In the scorched lands of the Immortal Bastion, Mordekaiser, the Iron Revenant, was amassing his undead army when he was challenged by a brave warrior. The warrior fought valiantly but was ultimately defeated, becoming another soldier in Mordekaiser's army.",
        "In the celestial realm, Bard, the Wandering Caretaker, was creating a new constellation when a rogue star threatened to disrupt his work. With a strum of his cosmic instrument, he set the star back on its course, preserving the harmony of the universe.",
        "In the city of Piltover, Caitlyn, the Sheriff of Piltover, was on the trail of a notorious thief. Using her superior tracking skills and precision shooting, she cornered the thief and brought him to justice.",
        "In the depths of the ocean, Fizz, the Tidal Trickster, was playing with his fellow sea creatures when a giant shark threatened them. With a playful leap and a quick trick, Fizz led the shark away, saving his friends.",
        "In the heart of Demacia, Garen, the Might of Demacia, was training his soldiers when a surprise attack came from Noxus. With a mighty roar and a whirl of his sword, Garen led his soldiers to repel the attack.",
        "In the mystical realm of Ionia, Irelia, the Blade Dancer, was practicing her dance when she sensed a disturbance. Using her psychic connection with her blades, she defended her village from a bandit raid.",
        "In the scorched lands of the Immortal Bastion, Sion, the Undead Juggernaut, was leading his undead army when he was challenged by a brave warrior. The warrior fought valiantly but was ultimately defeated, becoming another soldier in Sion's army.",
        "In the twisted realm of the Void, Vel'Koz, the Eye of the Void, was studying the physical realm when he encountered a group of explorers. Intrigued by their knowledge, he let them go, choosing to learn from them rather than destroy them.",
        "In the bustling city of Zaun, Vi, the Piltover Enforcer, was patrolling the streets when she spotted a gang causing trouble. With her powerful hextech gauntlets, she put a stop to their mischief and restored peace to the streets.",
        "In the ancient Shuriman desert, Xerath, the Magus Ascendant, was harnessing the power of the sun discs when he was interrupted by a group of tomb raiders. With a wave of his hand, he trapped them in a sandstorm, allowing him to continue his work undisturbed.",
        "In the mystical realm of Ionia, Ivern, the Green Father, was wandering through the forest when he stumbled upon a group of animals being threatened by a wildfire. With a wave of his hand, he commanded the plants to create a barrier, stopping the fire in its tracks and saving the animals. The grateful animals became his friends, and together they restored the forest to its former glory.",
        "In the icy tundra of the Freljord, Anivia, the Cryophoenix, was shaping the landscape when she noticed a village threatened by an avalanche. With a flap of her wings, she redirected the snowfall, saving the village."
    ],
    'Anime': [
        "In the bustling city of Tokyo, a high school student named Light Yagami stumbled upon a mysterious notebook known as the 'Death Note'. With the power to kill anyone whose name is written in it, Light decided to use the notebook to create a utopian world free of crime, becoming the vigilante known as 'Kira'.",
        "In a world where humanity has been pushed to the brink of extinction by giant humanoid creatures known as Titans, a young boy named Eren Yeager vowed to eradicate the Titans after witnessing the destruction of his hometown and the death of his mother.",
        "In the Hidden Leaf Village, a young, boisterous ninja named Naruto Uzumaki dreams of becoming the Hokage, the village's leader and strongest ninja. Despite the hardship and prejudice he faces due to the Nine-Tails sealed within him, Naruto never gives up on his dream.",
        "In a world where alchemy is a widely practiced science, two brothers, Edward and Alphonse Elric, attempted the forbidden act of human transmutation to bring their deceased mother back to life. The failed attempt resulted in Edward losing his arm and leg and Alphonse losing his entire body, setting them on a journey to find the Philosopher's Stone to restore their bodies.",
        "In a world where pirates roam the seas, a young man named Monkey D. Luffy dreams of finding the ultimate treasure, One Piece, and becoming the Pirate King. With his diverse crew of pirates, known as the Straw Hat Pirates, Luffy explores the Grand Line in search of the world's ultimate treasure.",
        "In a world where nearly everyone has superpowers, or 'Quirks', a young boy named Izuku Midoriya dreams of becoming a hero despite being born without a Quirk. His life changes when he meets his idol, All Might, who passes on his Quirk to Midoriya, allowing him to attend a prestigious high school for heroes in training.",
        // Existing stories...
        "In a world where magic is everything, a young boy named Asta dreams of becoming the Wizard King, the strongest mage in the kingdom. Despite being born without magic, Asta trains his physical strength and never gives up on his dream.",
        "In a world where humanity lives within enormous walled cities to protect themselves from Titans, gigantic humanoid creatures, a young boy named Eren Yeager dreams of joining the Scout Regiment to explore the world beyond the walls.",
        "In a world where virtual reality has been merged with reality, a high school student named Kirito becomes trapped in a virtual reality MMORPG game called Sword Art Online. The only way to escape is to clear the game, but death in the game means death in real life.",
        "In a world where people can become heroes based on their abilities, a young boy named Izuku Midoriya, who was born without any powers, is chosen by the greatest hero of all time, All Might, to become his successor and carry on his legacy.",
        "In a world where Shinigami, or death gods, exist, a high school student named Light Yagami discovers a Death Note, a notebook that kills anyone whose name is written in it. With this power, Light sets out to create a utopian world free from evil.",
        "In a world where humanity has been driven to the brink of extinction by monstrous humanoid creatures known as Titans, a young boy named Eren Yeager joins the military to fight against these monsters after his hometown is destroyed and his mother is killed.",
        "In a world where pirates roam the seas in search of treasure, a young boy named Monkey D. Luffy sets out on a journey to find the legendary treasure known as One Piece and become the Pirate King.",
        "In a world where superhuman abilities known as Quirks are the norm, a Quirkless boy named Izuku Midoriya dreams of becoming a hero. His life changes when he meets his idol, All Might, who passes on his Quirk to Izuku, allowing him to attend a prestigious high school for heroes in training.",
        "In a world where alchemy exists, two brothers, Edward and Alphonse Elric, embark on a journey to find the Philosopher's Stone to restore their bodies after a failed attempt to bring their mother back to life through alchemy.",
        "In a world where humanity is threatened by giant humanoid creatures known as Titans, a young boy named Eren Yeager joins the military to fight against these monsters after his hometown is destroyed and his mother is killed.",
        "In a world where magic exists and can be used for good or evil, a young boy named Asta, who is the only person in his world without any magic power, aims to become the Wizard King, the highest authority in his kingdom.",
        "In a world where virtual reality has been merged with reality, a high school student named Kirito becomes trapped in a virtual reality MMORPG game called Sword Art Online. The only way to escape is to clear the game, but death in the game means death in real life.",
        "In a world where Shinigami, or death gods, exist, a high school student named Light Yagami discovers a Death Note, a notebook that kills anyone whose name is written in it. With this power, Light sets out to create a utopian world free from evil.",
        "In a world where humanity has been driven to the brink of extinction by monstrous humanoid creatures known as Titans, a young boy named Eren Yeager joins the military to fight against these monsters after his hometown is destroyed and his mother is killed.",
        "In a world where pirates roam the seas in search of treasure, a young boy named Monkey D. Luffy sets out on a journey to find the legendary treasure known as One Piece and become the Pirate King.",
        "In a world where superhuman abilities known as Quirks are the norm, a Quirkless boy named Izuku Midoriya dreams of becoming a hero. His life changes when he meets his idol, All Might, who passes on his Quirk to Izuku, allowing him to attend a prestigious high school for heroes in training.",
        "In a world where alchemy exists, two brothers, Edward and Alphonse Elric, embark on a journey to find the Philosopher's Stone to restore their bodies after a failed attempt to bring their mother back to life through alchemy.",
        "In a world where humanity is threatened by giant humanoid creatures known as Titans, a young boy named Eren Yeager joins the military to fight against these monsters after his hometown is destroyed and his mother is killed.",
        "In a world where magic exists and can be used for good or evil, a young boy named Asta, who is the only person in his world without any magic power, aims to become the Wizard King, the highest authority in his kingdom.",
        "In a world where virtual reality has been merged with reality, a high school student named Kirito becomes trapped in a virtual reality MMORPG game called Sword Art Online. The only way to escape is to clear the game, but death in the game means death in real life."
    ]
}